config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :slots

  root to: 'home#index'
  get '/game', to: 'game#index'
  get '/help', to: 'game#help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'go_job' => 'game#go_job'
  get 'contemplate_nature' => 'game#contemplate_nature'
  get 'drink_wine_and_watch_tv_series' => 'game#drink_wine_and_watch_tv_series'
  get 'go_to_the_bar' => 'game#go_to_the_bar'
  get 'drink_with_marginal_people' => 'game#drink_with_marginal_people'
  get 'sing_in_the_subway' => 'game#sing_in_the_subway'
  get 'sleep' => 'game#sleep'
  get 'new_game' => 'game#new_game'
  post 'load_game' => 'slots#load_game'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
end

app/models/slot.rb
# frozen_string_literal: true

class Slot < ApplicationRecord
  def set_from_user(user, save_name)
    self.user_id = user.id
    self.health = user.health
    self.name = save_name
    self.mana = user.mana
    self.happiness = user.happiness
    self.money = user.money
    self.fatigue = user.fatigue
  end

  def base_init
    self.user_id = 0
    self.health = 100
    self.name = ''
    self.mana = 30
    self.happiness = 5
    self.fatigue = 0
    self.money = 5000
  end
end

app/models/user.rb
# frozen_string_literal: true

require_relative 'user_actions'
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  include UserActions
  def load_from_slot(slot)
    self.health = slot.health
    self.mana = slot.mana
    self.happiness = slot.happiness
    self.fatigue = slot.fatigue
    self.money = slot.money

    save
  end

  def init_stats
    self.health = 100
    self.mana = 30
    self.happiness = 5
    self.fatigue = 0
    self.money = 5000
    save
  end

  def apply_stats(health, mana, happiness, fatigue, money)
    self.health += health
    self.mana += mana
    self.happiness += happiness
    self.fatigue += fatigue
    self.money += money
    fix_stats
    save
  end

  def fix_mana
    if self.mana.negative?
      self.mana = 0
      self.happiness -= 1
    end

    if self.mana > 100
      self.health = self.health - ((self.mana - 100) / 4)
      self.mana = 100
    end
  end

  def fix_stats
    fix_mana

    self.health = 100 if self.health > 100
    self.health = 0 if self.health.negative?

    self.fatigue = 100 if self.fatigue > 100
    self.fatigue = 0 if self.fatigue.negative?

    self.happiness = 10 if self.happiness > 10
  end

  def check_win_lose
    if self.money >= 50_000
      save

      'Valera say: Finally!'
    elsif (self.happiness < -9) || (self.health < 1)
      save

      'Valera say: Farewell, cruel world...'
    else
      ''
    end
  end
end

app/models/user_actions.rb
# frozen_string_literal: true

module UserActions
  extend ActiveSupport::Concern
  def go_job
    if (mana > 50) || (fatigue > 60)
      'Valera say: Jjob?... W-what is it?'
    else
      apply_stats(0, -30, 0, 30, 1250)
      'Valera say: Its been a hard day'
    end
  end

  def contemplate_nature
    apply_stats(0, -10, 1, -10, 0)
    'Valera say: I wandered lonely as a cloud'
  end

  def drink_wine_and_watch_tv_series
    if money < 200
      'Valera say: Sorry, out of money'
    else
      apply_stats(-5, 30, 1, 10, -200)
      'Valera say: Ta-ta-tadada-ta...'
    end
  end

  def go_to_the_bar
    if money < 250
      'Valera say: Sorry, out of money'
    else
      apply_stats(-10, 60, 2, 40, -250)
      'Valera say: Beer or not two beer?'
    end
  end

  def drink_with_marginal_people
    if money < 1500
      'Valera say: Sorry, out of money'
    else
      apply_stats(-80, 90, 5, 80, -1500)
      'Valera say: Oj, MOROZ MOROOOOOZ...'
    end
  end

  def sing_in_the_subway
    if fatigue > 80
      'Valera say: I need to sleep, not sing'
    elsif (mana > 30) && (mana < 60)
      apply_stats(0, 0, 0, 0, +50)
      'Valera say: Near, far, wherever you are...'
    else
      apply_stats(0, -10, 1, 20, +10)
      'Valera say: IM GONNA ROCK!!!'
    end
  end

  def sleep
    if mana < 40
      apply_stats(90, -50, 0, -70, 0)
      'Valera say: zZzZzZ...'
    else
      apply_stats(0, -50, -3, -70, 0)
      'Valera say: zzz...one more shot...zzz'
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/game_controller.rb
# frozen_string_literal: true

class GameController < ApplicationController
  def index
    if user_session.nil?
      render plain: 'Error! You not authorized.', status: :unauthorized
      return
    end

    check_end_game
  end

  def check_end_game
    result = current_user.check_win_lose

    if result == ''
      @is_lose = false
    else
      flash.notice = result
      @is_lose = true
    end
  end

  def new_game
    current_user.init_stats

    redirect_to '/game'
  end

  def go_job
    flash.notice = current_user.go_job
    redirect_to '/game'
  end

  def contemplate_nature
    flash.notice = current_user.contemplate_nature
    redirect_to '/game'
  end

  def drink_wine_and_watch_tv_series
    flash.notice = current_user.drink_wine_and_watch_tv_series
    redirect_to '/game'
  end

  def go_to_the_bar
    flash.notice = current_user.go_to_the_bar
    redirect_to '/game'
  end

  def drink_with_marginal_people
    flash.notice = current_user.drink_with_marginal_people
    redirect_to '/game'
  end

  def sing_in_the_subway
    flash.notice = current_user.sing_in_the_subway
    redirect_to '/game'
  end

  def sleep
    flash.notice = current_user.sleep
    redirect_to '/game'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/slots_controller.rb
# frozen_string_literal: true

class SlotsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    if user_session.nil?
      render plain: 'Error! You not authorized.', status: :unauthorized
      return
    end

    saves_list = Slot.where(user_id: current_user.id).all
    @save_names_list = []

    saves_list&.each do |it|
      @save_names_list.append(it.name)
    end
  end

  def new
    return unless user_session.nil?

    render plain: 'Error! You not authorized.', status: :unauthorized
  end

  def create
    if params[:save_form][:name_save] == ''
      flash.alert = 'Invalid name save!'
      render 'new'
    else
      slot = Slot.find_by(name: params[:save_form][:name_save])

      if slot.nil?
        create_new_slot
      else
        rewrite_slot(slot)
      end
    end
  end

  def create_new_slot
    slot = Slot.new
    slot.set_from_user(current_user, params[:save_form][:name_save])

    slot.save

    Slot.first.delete if Slot.count > 3

    redirect_to '/game'
  end

  def rewrite_slot(slot)
    slot.set_from_user(current_user, params[:save_form][:name_save])
    slot.save
    redirect_to '/game'
  end

  def load_game
    user_saves_list = Slot.where(user_id: current_user.id).all
    slot = user_saves_list.find_by(name: params[:load_form][:saves_list])

    current_user.load_from_slot(slot)

    redirect_to '/game'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/game/help.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
</head>
    <body>
        <div class = "six"><h1><span>HELP</span></h1><table class = "tab-cent" align="right">
            <tr>
                <th>
                    <h4 class = "style_h4">Sing in the subway </h4>
                </th>
                <th>
                    <h4 class = "style_h4">Sleep</h4>
                </th>
            </tr>
            <tr>
                <td>
                   <div class = "p_help"; style="color:#D2691E;">+1 Happiness</div>
                    <div class = "p_help"; style="color:#000080;">+10 Mana</div>
                    <div class = "p_help"; style="color:#00FF00;">+$10 (+ $ 50 more if initially mana was > 40 & <70 ) </div>
                    <div class = "p_help"; style="color:#8B4513;">+20 Fatigue</div>
                </td>
                <td>
                   <div class = "p_help"; style="color:#FF0000;">+90 Health (if mana was < 30)</div>
                    <div class = "p_help"; style="color:#D2691E;">-3 Happiness</div>
                    <div class = "p_help"; style="color:#000080;">-50 Mana </div>
                    <div class = "p_help"; style="color:#8B4513;">-70 Fatigue</div>
                </td>
        </table></div>

        <table>
        <tr>
            <th>
                <h4 class = "style_h4">Go to job</h4><h6 class = "style_h6">Condition: Only possible if mana <50 and fatigue <10 </h6> 
            </th>
            <th>
                <h4 class = "style_h4">Contemplate nature </h4>
            </th>
            <th>
                <h4 class = "style_h4">Drink wine and watch TV series </h4>
            </th>
            <th>
                <h4 class = "style_h4">Go to a bar </h4>
            </th>
            <th>
                <h4 class = "style_h4">Drink with marginal people</h4><h6 class = "style_h6">Condition: If the money is not > 1500 </h6>
            </th>

        </tr>

        <tr>
            <td> 
                <div class = "p_help"; style="color:#D2691E;">-5 Happiness</div>
                <div class = "p_help"; style="color:#000080;">-30 Mana</div>
                <div class = "p_help"; style="color:#00FF00;">+$100</div>
                <div class = "p_help"; style="color:#8B4513;">+70 Fatigue</div>
            </td>
            <td>
                <div class = "p_help"; style="color:#D2691E;">+1 Happiness</div>
                <div class = "p_help"; style="color:#000080;">-10 Mana</div>
            <div class = "p_help"; style="color:#8B4513;">+10 Fatigue</div>
            </td>
            <td>
                <div class = "p_help"; style="color:#D2691E;">+1 Happiness</div>
                <div class = "p_help"; style="color:#000080;">+30 Mana</div>
                <div class = "p_help"; style="color:#8B4513;">+10 Fatigue</div>
                <div class = "p_help"; style="color:#FF0000;">-5 Health</div>
                <div class = "p_help"; style="color:#00FF00;">-$20</div>
            </td>
            <td>
               <div class = "p_help"; style="color:#D2691E;">+2 Happiness</div>
                <div class = "p_help"; style="color:#000080;">+60 Mana</div>
                <div class = "p_help"; style="color:#8B4513;">+40 Fatigue</div>
                <div class = "p_help"; style="color:#FF0000;">-10 Health</div>
                <div class = "p_help"; style="color:#00FF00;">-$100</div>
            </td>
            <td>
                <div class = "p_help"; style="color:#D2691E;">+5 Happiness</div>
                <div class = "p_help"; style="color:#FF0000;">-80 Health</div>
                <div class = "p_help"; style="color:#000080;">+90 Mana</div>
                <div class = "p_help"; style="color:#8B4513;">+80 Fatigue</div>
                <div class = "p_help"; style="color:#00FF00;">-$150</div>
            </td>
        </tr> 
        </table>
        <br>
        <hr border = 5px>
        <h1 align = "center">Description of the game</h1>
        <p class = "descp" align = "center"> Meet Valera, he is good-natured, clumsy and gets into the strangest situations.</p>
        <p class = "descp"> As one person said: "I have a dream...". Valera also has one. He dreams of his first car. Help Valera make his dream come true.</p>
        <p class = "descp">Goal: save 50,000 rubles for a car.</p>

    </body>
</html>

app/views/game/index.html.erb
<title>Game Valera</title>
<% name = current_user.present? ? current_user.name : 'Stranger'%>
<h6 align="center", class="nav-item">
    <h>Valera Life Stats</h>
    <p class = "health">Health: <progress class="health-roll" value="<%= current_user.health %>" max="100"></progress><p> 
    <p class = "mana">Mana: <progress class="mana-roll" value="<%= current_user.mana %>" max="100"></progress><p>
    <% if current_user.happiness.positive? or current_user.happiness.zero?%>
        <p class = "happines">Happiness: <progress class="happiness1-roll" value="<%= current_user.happiness %>" max="10"></progress><p>
    <%end%>
    <% if current_user.happiness.negative? %>
        <p class = "sadness">Sadness: <progress class="happiness2-roll" value="<%= current_user.happiness.abs %>" max="10"></progress><p>
    <%end%>
    <p class = "fatigue">Fatique: <progress class="fatigue-roll" value="<%= current_user.fatigue %>" max="100"></progress><p>
    <p class = "money">Money: <%= current_user.money %>₽<p>
</h6>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info" align = "center">
        <%= msg %>
      </div>
    <% end %>
<h6 align="center", class="nav-item">
        <button><%= link_to 'New Game', new_game_path, method: :get, class: "link"%></button>
        <% if !@is_lose %>
            <button><%= link_to "Save Game", new_slot_path, class: "link" %></button>
        <% end %>
        <button><%= link_to "Load Game", slots_path, class: "link" %></button>
    <li><button class="new-button"><%= link_to 'Go Job', go_job_path, class: "link", method: :get if !@is_lose %></button></li>
    <li><button class="new-button"><%= link_to 'Contemplate nature', contemplate_nature_path, class: "link", method: :get if !@is_lose%></button></li>
    <li><button class="new-button"><%= link_to 'Drink wine and watch TV series', drink_wine_and_watch_tv_series_path, class: "link", method: :get if !@is_lose%></button></li>
    <li><button class="new-button"><%= link_to 'Go to the bar', go_to_the_bar_path, class: "link", method: :get if !@is_lose%></button></li>
    <li><button class="new-button"><%= link_to 'Drink with marginal people', drink_with_marginal_people_path, class: "link", method: :get if !@is_lose%></button></li> 
    <li><button class="new-button"><%= link_to 'Sing in the subway', sing_in_the_subway_path, class: "link", method: :get if !@is_lose%></button></li>
    <li><button class="new-button"><%= link_to 'Sleep', sleep_path, class: "link", method: :get if !@is_lose%></button></li>
</h6> 

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.name : 'Stranger'%>
<h1 align="center" class="greetings">VALERA</h1>
<h2 align="center">BEST GAME EVER</h2>
<h3 align="center">Welcome, <%= name %></h3>
<% if user_signed_in? %>
	<h3 align="center"> 
		<button class="nav-item">
			<%= link_to "Game", game_path, class:'nav-link'%>
		</button>
	</h3>
<%else%>
	<h3 align="center"> 
		<button class="nav-item">
			<%= link_to "Please, sign in to play", new_user_session_path, class:'nav-link'%>
		</button>
	</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Valera</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Valera</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Gamе', game_path, class:'nav-link'%>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link'%>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Help', help_path, class: 'nav-link'%>
      </li>  
    </ul>
  </div>
</nav>

app/views/slots/index.html.erb
  <h2>Load Game</h2>

  <div align="center">
    <%= form_with scope: :load_form, url: "load_game" do |f| %>
        <tr>
          <td align="center" colspan="3">
            <%= f.select :saves_list, @save_names_list, {:multiple => false}, {class: "list-width"}  %>
		      </td>
        </tr>
            <td colspan="2" align="center">
              <div class="container"><%= flash.alert %></div>
            </td>
      <li class="nav-item">
        <li><%= f.submit :"Load Game", value: "Load Game", class: "round-button-marginal" %></li>
        <li><%= link_to "Cancel", game_path %></li>
      </li> 
    <% end %>
  </div>

app/views/slots/new.html.erb
  <h2>Save game</h2>

  <div align="center">
    <%= form_with scope: :save_form, url: slots_path, local: true do |f| %>
        <li class="nav-item">
          <%= f.label :name_save %><br />
          <td><%= f.text_field :name_save, class: "round" %></td>
        </li>
          <td colspan="2">
            <div align="center" class="round"><%= flash.alert %></div>
          </td>
      <li class="nav-item">
        <li><button class="new-button"><%= f.submit :"Save Game", value: "Save Game", class: "round" %></button></li>
        <li><%= link_to "Cancel", game_path %></li>
      </li> 
    <% end %>
  </div>